name: Android Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # ここで環境変数として定義することで、下の if 文で使えるようになります
    env:
      KEYSTORE_B64: ${{ secrets.KEYSTORE_BASE64 }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.13

      - name: Decode keystore
        if: ${{ env.KEYSTORE_B64 != '' }}
        run: |
          # app/ の中に作成
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore

      - name: Create keystore properties
        if: ${{ env.KEYSTORE_B64 != '' }}
        run: |
          # app/ の中に作成
          cat > app/keystore.properties <<'PROPS'
          storeFile=release.keystore
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          PROPS

      - name: Build release APK
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/android-music-player-*.apk
